version: "3.3"
services:
    influxdb:
      container_name: influxdb
      image: influxdb
      volumes:
        - vol_influx:/var/lib/influxdb
      ports:
        - 18086:8086
        - 12003:2003
        - 18083:8083
      environment:
        - INFLUXDB_GRAPHITE_ENABLED=true
        - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_DB=slimmemeter
        - INFLUXDB_ADMIN_USER=root
        - INFLUXDB_ADMIN_PASSWORD=123
        - INFLUXDB_USER=slimmemeter
        - INFLUXDB_USER_PASSWORD=123

    grafana:
      container_name: spine_grafana
      image: grafana/grafana
      volumes:
        - vol_grafana:/var/lib/grafana
      ports:
        - 13000:3000
      environment:
        - GF_SERVER_ROOT_URL=localhost:13000
        - GF_SECURITY_ADMIN_PASSWORD=123

volumes: 
  vol_influx:
  vol_grafana: